name: 'Get and cache dependencies'
description: 'Get the dependencies (via pip) and cache them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      run: |
        python -m pip install --upgrade pip
      shell: bash
    - name: Install dependencies
      run: |
        if [ "${{ inputs.caching }}" == "true" ]; then
          echo "Caching enabled, installing dependencies with cache..."
        else
          echo "Installing dependencies without caching..."
        fi
        pip install -r requirements.txt
      shell: bash
