name: Deployment
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint Code
        run: black --check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache and Install Dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: "true"

      - name: Run Tests
        run: |
          pytest tests --cov=.
          coverage report -m
