name: Deployment
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache and Install Dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: "true"
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs}}"
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Lint Code
        run: black --check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache and Install Dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: "true"
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs}}"
      - name: Install pytest and coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
      - name: Run Tests
        run: |
          pytest tests --cov=.
